__default__:
  partition: normal
  time: "02:00:00"
  cpus-per-task: 4
  mem: "16G"

flye_draft_assembly:
  time: "24:00:00"
  cpus-per-task: 8
  mem: "8G"

medaka_correction:
  time: "06:00:00"
  cpus-per-task: 4
  mem: "8G"

pilon_polishing:
  time: "06:00:00"
  cpus-per-task: 4
  mem: "16G"

ragtag_scaffolding:
  time: "01:00:00"
  cpus-per-task: 1
  mem: "8G"

tgs_gapcloser:
  time: "06:00:00"
  cpus-per-task: 4
  mem: "16G"
